language: cpp
compiler:
  - clang
notifications:
  email: false

before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/julianightlies -y
  - sudo apt-get update -qq -y
  - sudo apt-get -qq install gdb cmake libssh2-1-dev openssh-client openssh-server
  - sudo apt-get install libpcre3-dev julia

script:
  - git submodule init
  - git submoudle update
  - julia -e 'Pkg.init(); 
              run(`ln -s $(pwd()) $(Pkg.dir("LibGit2"))`);
              Pkg.pin("LibGit2");
              Pkg.resolve();'
  - julia -e 'Pkg.build("LibGit2")'
  - julia -e 'using LibGit2; @assert isdefined(:LibGit2); @assert typeof(LibGit2) === Module'
  - cd test/
  - git config --global user.name "testfirst testlast" 
  - julia --code-coverage runtests.jl all
# - sh run_remote_clone.sh
  - cd ../
  - julia -e 'Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
